[package]
name = "cli_hunter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.5", features = ["derive","wrap_help"] }
scraper = "0.20.0"
ureq = "2.10.1"
url = "2.5.2"
